import { AppDataSource } from '../config/database';
import { Pipeline } from '../models/Pipeline';
import { Repository } from '../models/Repository';
import { aiService } from './ai.service';
import { githubService } from './github.service';

export class CICDService {
  async generatePipeline(repositoryId: string, accessToken: string): Promise<Pipeline> {
    const repoRepo = AppDataSource.getRepository(Repository);
    const pipelineRepo = AppDataSource.getRepository(Pipeline);

    const repo = await repoRepo.findOne({ where: { id: repositoryId } });
    if (!repo) throw new Error('Repository not found');

    const [owner, repoName] = repo.fullName.split('/');
    const contents = await githubService.getRepoContents(accessToken, owner, repoName);
    const items = contents as Array<{ name: string; type: string }>;
    const fileStructure = items.map((i) => `${i.type === 'dir' ? '📁' : '📄'} ${i.name}`).join('\n');
    const framework = this.detectFramework(items);

    const result = await aiService.generateCICDPipeline(repo.fullName, repo.language ?? null, fileStructure, framework);

    const pipeline = pipelineRepo.create({
      repository: repo,
      name: `CI/CD for ${repo.name}`,
      content: result.workflow,
      techStack: repo.language || 'unknown',
      status: 'draft',
    });
    await pipelineRepo.save(pipeline);
    return pipeline;
  }

  async deployPipeline(pipelineId: string, repositoryId: string, accessToken: string): Promise<{ prUrl: string }> {
    const pipelineRepo = AppDataSource.getRepository(Pipeline);
    const repoRepo = AppDataSource.getRepository(Repository);

    const pipeline = await pipelineRepo.findOne({ where: { id: pipelineId } });
    const repo = await repoRepo.findOne({ where: { id: repositoryId } });
    if (!pipeline || !repo) throw new Error('Pipeline or repository not found');

    const [owner, repoName] = repo.fullName.split('/');
    const branchName = `feature/add-cicd-pipeline-${Date.now()}`;
    const sha = await githubService.getLatestCommitSha(accessToken, owner, repoName, repo.defaultBranch);

    await githubService.createBranch(accessToken, owner, repoName, branchName, sha);
    await githubService.createOrUpdateFile(
      accessToken, owner, repoName, '.github/workflows/ci-cd.yml',
      'Add CI/CD pipeline generated by GitHub AI DevOps Platform',
      pipeline.content, branchName
    );

    const pr = await githubService.createPullRequest(
      accessToken, owner, repoName,
      '🤖 Add AI-Generated CI/CD Pipeline',
      `## Summary\n\nThis PR adds an AI-generated CI/CD pipeline.\n\n**Tech Stack:** ${pipeline.techStack}\n\n---\n*Generated by GitHub AI DevOps Platform*`,
      branchName, repo.defaultBranch
    );

    pipeline.prUrl = pr.html_url;
    pipeline.status = 'deployed';
    await pipelineRepo.save(pipeline);
    return { prUrl: pr.html_url };
  }

  private detectFramework(contents: Array<{ name: string }>): string | null {
    const names = contents.map((f) => f.name);
    if (names.includes('package.json')) return 'Node.js';
    if (names.includes('requirements.txt') || names.includes('setup.py')) return 'Python';
    if (names.includes('pom.xml') || names.includes('build.gradle')) return 'Java';
    if (names.includes('go.mod')) return 'Go';
    if (names.includes('Cargo.toml')) return 'Rust';
    return null;
  }
}

export const cicdService = new CICDService();
